### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'bq'

### ISSUE THREAD

**Issue by ryptozee** [EvgSkv/logica#27]
Whenever example command `logica primes.l run Prime` is executed, error is produced:
`FileNotFoundError: [Errno 2] No such file or directory: 'bq'`

It happens in docker container ubuntu:latest with python3.8.5 installed

Please see the log output:

```
root@d0094b59f905:/home# logica primes.l run Prime
Traceback (most recent call last):
  File "/usr/local/bin/logica", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.8/dist-packages/logica/logica.py", line 184, in run_main
    main(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/logica/logica.py", line 157, in main
    p = subprocess.Popen(['bq', 'query',
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bq'
```

**Comment by EvgSkv** [comment]
As [Prerequisites](https://github.com/EvgSkv/logica#prerequisites) section states we need to install Google Cloud SDK to execute on BigQuery.

I agree that on-boarding should be made easier. Keeping the issue open, as we need to try to do more things automatically.

**Comment by happy15** [comment]
I just tried the example of primes locally and it gave me this error.  

Do I need Google Cloud SDK for this?

**Comment by EvgSkv** [comment]
Hello @happy15 !
You don't need Google SDK to run Logica. :-)

Just specify an engine that works locally. SQLite comes with Python. Or you can install DuckDB for faster speed and more robust handling of complex aggregation.

E.g. create file `primes.l` with content:

```
@Engine("sqlite");  # <-- using SQLite.

# Define numbers 1 to 30.
Number(x + 1) :- x in Range(30);

# Defining composite numbers.
Composite(a * b) distinct :- Number(a), Number(b), a > 1, b > 1;

# Defining primes as "not composite".
Prime(n) distinct :- Number(n), n > 1, ~Composite(n);
```

Then run:
```
python3 -m logica primes.l run Prime
```

Let me know if you have further questions!
